# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. T. Chaitanya Sagar
subtitle: Computational Materials Researcher
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
#url: ""
url: "https://sagarchaitanya.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: sagarchaitanya
author_logo: /assets/logo.jpg
author: sagarchaitanya
author_email: "chaitanya.sagar@uohyd.ac.in;me14resch11007@iith.ac.in"
author_location: Hyderabad, India
author_website_url: "https://sagarchaitanya.github.io/"
#show_excerpts: false # set to true to show excerpts on the homepage
# Disqus for commenting under the post
disqus_shortname: chaitanya-sagar

## social links
twitter_username: chaitanyasagar7
github_username: sagarchaitanya
facebook_username: chaitanyasagar.tinku
linkedin_username: sagarchaitanya

# Google Analytics
google_analytics: G-7YYYJT5B00

# Additional plugins
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

# Build setting
permalink: pretty # remove *.html extension from generated link
markdown: kramdown

highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  syntax_highlighter_opts: {span: {disable: true}}
  math_engine: mathjax


#github_username: sagarchaitanya
#ORCID: (https://orcid.org/0000-0001-5522-3373)
#LinkedIN:  https://www.linkedin.com/in/sagarchaitanya
#collections: [sections]
# Build settings
#theme: forty_jekyll_theme
  #minima


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#theme: minima
